services:
  - type: web
    name: mesh-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/actuator/health
    envVars:
      - key: MESH_DATABASE_URL
        sync: false
      - key: MESH_DATABASE_USERNAME
        sync: false
      - key: MESH_DATABASE_PASSWORD
        sync: false
      - key: MESH_JWT_SECRET
        generateValue: true
      - key: MESH_ALLOWED_ORIGINS
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_REDIRECT_URI
        sync: false
      - key: GITHUB_SUCCESS_REDIRECT_URI
        sync: false
      - key: GITHUB_ERROR_REDIRECT_URI
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: DISCORD_SUCCESS_REDIRECT_URI
        sync: false
      - key: DISCORD_ERROR_REDIRECT_URI
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DISCORD_CATEGORY_ID
        sync: false
