-- Mesh Connect initial schema.
--
-- Written in portable ANSI SQL (identity columns, `timestamp with time zone`)
-- so this single migration builds both the embedded H2 development database and
-- the PostgreSQL production database. Nothing here is vendor specific.

create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    email varchar(160) not null unique,
    password_hash varchar(100) not null,
    role varchar(20) not null default 'STUDENT',
    active boolean not null default true,
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint ck_app_users_role check (role in ('STUDENT', 'ADMIN'))
);

create table profiles (
    user_id bigint primary key references app_users(id) on delete cascade,
    display_name varchar(80) not null,
    department varchar(100),
    year_of_study integer,
    bio varchar(500),
    availability varchar(80),
    avatar_key varchar(40),
    onboarding_complete boolean not null default false,
    updated_at timestamp(6) with time zone not null default current_timestamp,
    constraint ck_profiles_year check (year_of_study is null or year_of_study between 1 and 6)
);

create table skills (
    id bigint generated by default as identity primary key,
    name varchar(80) not null unique,
    category varchar(60) not null default 'General'
);

create table user_skills (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id) on delete cascade,
    skill_id bigint not null references skills(id) on delete restrict,
    proficiency integer not null,
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint ck_user_skills_proficiency check (proficiency between 1 and 5),
    constraint uq_user_skill unique (user_id, skill_id)
);

-- A directed "I would like to work with you" signal. The unique constraint keeps
-- one row per direction; a match is created once both directions exist.
create table interests (
    id bigint generated by default as identity primary key,
    sender_id bigint not null references app_users(id) on delete cascade,
    receiver_id bigint not null references app_users(id) on delete cascade,
    status varchar(20) not null default 'PENDING',
    created_at timestamp(6) with time zone not null default current_timestamp,
    updated_at timestamp(6) with time zone not null default current_timestamp,
    constraint ck_interests_distinct_users check (sender_id <> receiver_id),
    constraint ck_interests_status check (status in ('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED')),
    constraint uq_interest_direction unique (sender_id, receiver_id)
);

-- Members are stored in ascending id order so an unordered pair has exactly one
-- row. The check constraint makes a duplicate or reversed pair impossible in the
-- database itself rather than relying on application code to be careful.
create table matches (
    id bigint generated by default as identity primary key,
    user_one_id bigint not null references app_users(id) on delete cascade,
    user_two_id bigint not null references app_users(id) on delete cascade,
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint ck_matches_canonical_pair check (user_one_id < user_two_id),
    constraint uq_match_pair unique (user_one_id, user_two_id)
);

create table messages (
    id bigint generated by default as identity primary key,
    match_id bigint not null references matches(id) on delete cascade,
    sender_id bigint not null references app_users(id) on delete cascade,
    content varchar(2000) not null,
    sent_at timestamp(6) with time zone not null default current_timestamp,
    read_at timestamp(6) with time zone
);

create table posts (
    id bigint generated by default as identity primary key,
    author_id bigint not null references app_users(id) on delete cascade,
    kind varchar(20) not null,
    title varchar(160) not null,
    body varchar(4000) not null,
    category varchar(80),
    tags varchar(500),
    status varchar(20) not null default 'OPEN',
    solved_comment_id bigint,
    created_at timestamp(6) with time zone not null default current_timestamp,
    updated_at timestamp(6) with time zone not null default current_timestamp,
    constraint ck_posts_kind check (kind in ('HELP', 'PROJECT', 'SHOWCASE')),
    constraint ck_posts_status check (status in ('OPEN', 'SOLVED', 'CLOSED'))
);

create table comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null references posts(id) on delete cascade,
    author_id bigint not null references app_users(id) on delete cascade,
    body varchar(2000) not null,
    created_at timestamp(6) with time zone not null default current_timestamp
);

-- Added after `comments` exists because the two tables reference each other.
alter table posts add constraint fk_posts_solved_comment
    foreign key (solved_comment_id) references comments(id) on delete set null;

create table blocks (
    id bigint generated by default as identity primary key,
    blocker_id bigint not null references app_users(id) on delete cascade,
    blocked_id bigint not null references app_users(id) on delete cascade,
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint ck_blocks_distinct_users check (blocker_id <> blocked_id),
    constraint uq_block_pair unique (blocker_id, blocked_id)
);

create table reports (
    id bigint generated by default as identity primary key,
    reporter_id bigint not null references app_users(id) on delete cascade,
    target_type varchar(20) not null,
    target_id bigint not null,
    reason varchar(500),
    status varchar(20) not null default 'OPEN',
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint ck_reports_target_type check (target_type in ('USER', 'POST', 'COMMENT', 'MESSAGE')),
    constraint ck_reports_status check (status in ('OPEN', 'REVIEWED', 'DISMISSED'))
);

-- Indexes chosen for the queries the application actually issues: skill lookup
-- during recommendation, the interest inbox, conversation reads and feed paging.
create index idx_user_skills_skill_user on user_skills(skill_id, user_id);
create index idx_user_skills_user on user_skills(user_id);
create index idx_interests_receiver_status on interests(receiver_id, status);
create index idx_interests_sender_status on interests(sender_id, status);
create index idx_matches_user_one on matches(user_one_id);
create index idx_matches_user_two on matches(user_two_id);
create index idx_messages_match_sent on messages(match_id, sent_at);
create index idx_posts_created_at on posts(created_at desc);
create index idx_comments_post_created on comments(post_id, created_at);
create index idx_blocks_blocker_blocked on blocks(blocker_id, blocked_id);
create index idx_reports_status_created on reports(status, created_at);
